# Generated by Django 4.0.6 on 2022-08-08 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(default='xxxxx@wustl.edu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(default='Uncle Joe', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='student_id',
            field=models.CharField(default='xxxxxx', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
