# Generated by Django 4.0.6 on 2022-08-13 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited', models.BooleanField(default=False)),
                ('q1response', models.TextField()),
                ('applicant', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
            ],
        ),
    ]
