# Generated by Django 4.0.6 on 2022-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_alter_applicant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='points',
        ),
        migrations.AddField(
            model_name='applicant',
            name='round1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='round2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='q2response',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='q3response',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='q4response',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='q5elaboration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='q5response',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='scenarioquestions',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='writtenapp',
            name='scenariovalidation',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='writtenapp',
            name='q1response',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
