# Generated by Django 4.0.6 on 2022-08-27 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0005_alter_applicant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='xxxxx@wustl.edu', max_length=100, unique=True)),
                ('name', models.CharField(default='Uncle Joe', max_length=200)),
                ('round1_roster', models.ManyToManyField(null=True, related_name='first_round_roster', to='applicants.applicant')),
                ('round2_roster', models.ManyToManyField(null=True, related_name='second_round_roster', to='applicants.applicant')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('x_list', models.ManyToManyField(related_name='uninterviewable_pair', to='applicants.applicant')),
            ],
        ),
    ]
