# Generated by Django 4.0.6 on 2022-08-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_remove_applicant_points_applicant_round1_and_more'),
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='x_list',
        ),
        migrations.CreateModel(
            name='x_pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actives.active')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='round1_roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a1', to='applicants.applicant')),
                ('a2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a2', to='applicants.applicant')),
                ('a3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a3', to='applicants.applicant')),
            ],
        ),
    ]
